language: android
script: gradle build
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.3
    - android-24
licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

 
